from dotenv import load_dotenv
from os import getenv

load_dotenv()

PRODUCT_NAME = getenv("PRODUCT_NAME", "taka")
MONGO_URI = getenv("MONGO_URI")
MONGO_DATABASE = getenv("MONGO_DATABASE")
CHROMADB_HOST = getenv("CHROMADB_HOST")
CHROMADB_PORT = getenv("CHROMADB_PORT")
OLLAMA_MODEL = getenv("OLLAMA_MODEL")
MONGO_NAME_PERSONALITY = getenv("MONGO_NAME_PERSONALITY")
MONITOR_CHANGES_OBSERVER_PATH = getenv("MONITOR_CHANGES_OBSERVER_PATH")
